# Generated by Django 2.2.4 on 2019-08-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190812_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='previewtext',
            field=models.TextField(default='bleh'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateTimeField(default='01/01/2001'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='link',
            field=models.URLField(default='http://salut.com'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='location',
            field=models.TextField(default='rien'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='occasion',
            field=models.TextField(default='rien'),
        ),
    ]
